import type { ChatMessage, ChatRoom } from "../types";

// ═══════════════ Mock Chat Rooms ═══════════════

export const mockChatRooms: ChatRoom[] = [
  // ── Channels ──
  {
    id: "room_all",
    store_id: "store1",
    type: "channel",
    name: "全体連絡",
    member_ids: ["cast_mama1", "cast1", "cast2"],
    member_names: ["さくら（ママ）", "あかり", "みさき"],
    visible_to_seniors: true,
    created_at: "2026-01-01T00:00:00+09:00",
    last_message: {
      content: "明日のシフト確認お願いします",
      sender_name: "さくら（ママ）",
      sent_at: "2026-03-19T14:00:00+09:00",
    },
  },
  {
    id: "room_shift",
    store_id: "store1",
    type: "channel",
    name: "シフト相談",
    member_ids: ["cast_mama1", "cast1", "cast2"],
    member_names: ["さくら（ママ）", "あかり", "みさき"],
    visible_to_seniors: true,
    created_at: "2026-01-01T00:00:00+09:00",
    last_message: {
      content: "来週の金曜、お手伝いお願いできる？",
      sender_name: "あかり",
      sent_at: "2026-03-18T11:30:00+09:00",
    },
  },
  {
    id: "room_customer_share",
    store_id: "store1",
    type: "channel",
    name: "顧客情報共有",
    member_ids: ["cast_mama1", "cast1", "cast2"],
    member_names: ["さくら（ママ）", "あかり", "みさき"],
    visible_to_seniors: true,
    created_at: "2026-01-01T00:00:00+09:00",
    last_message: {
      content: "田中様、来週の水曜に来店予定です。お姉さんのテーブルに案内お願い",
      sender_name: "さくら（ママ）",
      sent_at: "2026-03-19T15:00:00+09:00",
    },
  },

  // ── DMs ──
  {
    id: "dm_mama_akari",
    store_id: "store1",
    type: "dm",
    name: null,
    member_ids: ["cast_mama1", "cast1"],
    member_names: ["さくら（ママ）", "あかり"],
    visible_to_seniors: false,
    created_at: "2026-02-01T00:00:00+09:00",
    last_message: {
      content: "渡辺様の同伴の件、ありがとう。来月もよろしくね",
      sender_name: "さくら（ママ）",
      sent_at: "2026-03-19T16:00:00+09:00",
    },
  },
  {
    id: "dm_akari_misaki",
    store_id: "store1",
    type: "dm",
    name: null,
    member_ids: ["cast1", "cast2"],
    member_names: ["あかり", "みさき"],
    visible_to_seniors: true, // ママ・お姉さんが見れる
    created_at: "2026-02-15T00:00:00+09:00",
    last_message: {
      content: "明日のT3のお客様、お酒弱めだから最初は薄めで作ってね",
      sender_name: "あかり",
      sent_at: "2026-03-19T17:30:00+09:00",
    },
  },
];

// ═══════════════ Mock Chat Messages ═══════════════

export const mockChatMessages: ChatMessage[] = [
  // ── room_all: 全体連絡 ──
  {
    id: "msg_1",
    room_id: "room_all",
    sender_id: "cast_mama1",
    sender_name: "さくら（ママ）",
    sender_role: "mama",
    content: "みなさん、おはようございます。今週末は予約が多いのでシフトの確認をお願いします。",
    thread_parent_id: null,
    reply_count: 2,
    mentions_ai: false,
    is_bot: false,
    created_at: "2026-03-19T10:00:00+09:00",
  },
  {
    id: "msg_2",
    room_id: "room_all",
    sender_id: "cast1",
    sender_name: "あかり",
    sender_role: "oneesan",
    content: "確認しました！金曜と土曜は入れます🌸",
    thread_parent_id: "msg_1",
    reply_count: 0,
    mentions_ai: false,
    is_bot: false,
    created_at: "2026-03-19T10:15:00+09:00",
  },
  {
    id: "msg_3",
    room_id: "room_all",
    sender_id: "cast2",
    sender_name: "みさき",
    sender_role: "help",
    content: "土曜はOKです。金曜は確認します！",
    thread_parent_id: "msg_1",
    reply_count: 0,
    mentions_ai: false,
    is_bot: false,
    created_at: "2026-03-19T10:20:00+09:00",
  },
  {
    id: "msg_4",
    room_id: "room_all",
    sender_id: "cast_mama1",
    sender_name: "さくら（ママ）",
    sender_role: "mama",
    content: "明日のシフト確認お願いします",
    thread_parent_id: null,
    reply_count: 0,
    mentions_ai: false,
    is_bot: false,
    created_at: "2026-03-19T14:00:00+09:00",
  },

  // ── room_customer_share: 顧客情報共有 ──
  {
    id: "msg_cs_1",
    room_id: "room_customer_share",
    sender_id: "cast1",
    sender_name: "あかり",
    sender_role: "oneesan",
    content: "山本様が今週また来るみたい。ポルシェの話で盛り上がったから、次も車の話題で入ると良いかも",
    thread_parent_id: null,
    reply_count: 1,
    mentions_ai: false,
    is_bot: false,
    created_at: "2026-03-19T12:00:00+09:00",
  },
  {
    id: "msg_cs_2",
    room_id: "room_customer_share",
    sender_id: "cast2",
    sender_name: "みさき",
    sender_role: "help",
    content: "了解です！山本様のマッカラン、残り少なかったので追加キープ提案してみますか？",
    thread_parent_id: "msg_cs_1",
    reply_count: 0,
    mentions_ai: false,
    is_bot: false,
    created_at: "2026-03-19T12:10:00+09:00",
  },
  {
    id: "msg_cs_3",
    room_id: "room_customer_share",
    sender_id: "cast1",
    sender_name: "あかり",
    sender_role: "oneesan",
    content: "@さくらママ 山本様にボトルの追加キープを提案するタイミングはいつがベスト？",
    thread_parent_id: null,
    reply_count: 1,
    mentions_ai: true,
    is_bot: false,
    created_at: "2026-03-19T12:15:00+09:00",
  },
  {
    id: "msg_cs_4",
    room_id: "room_customer_share",
    sender_id: "sakura_mama",
    sender_name: "さくらママ",
    content: "山本様はVIPだから、残りが3杯以下になったタイミングがベストよ。「いつものを準備しておきますね」って自然に切り出すの。今のタイミングだと「この前のポルシェの話の続き、聞かせてくださいね。いつものマッカランも用意しておきますから」って感じかしら🌸",
    thread_parent_id: "msg_cs_3",
    reply_count: 0,
    mentions_ai: false,
    is_bot: true,
    created_at: "2026-03-19T12:15:30+09:00",
  },
  {
    id: "msg_cs_5",
    room_id: "room_customer_share",
    sender_id: "cast_mama1",
    sender_name: "さくら（ママ）",
    sender_role: "mama",
    content: "田中様、来週の水曜に来店予定です。お姉さんのテーブルに案内お願い",
    thread_parent_id: null,
    reply_count: 0,
    mentions_ai: false,
    is_bot: false,
    created_at: "2026-03-19T15:00:00+09:00",
  },

  // ── dm_mama_akari ──
  {
    id: "msg_dm1_1",
    room_id: "dm_mama_akari",
    sender_id: "cast_mama1",
    sender_name: "さくら（ママ）",
    sender_role: "mama",
    content: "あかり、今月の同伴の進捗はどう？",
    thread_parent_id: null,
    reply_count: 0,
    mentions_ai: false,
    is_bot: false,
    created_at: "2026-03-19T15:30:00+09:00",
  },
  {
    id: "msg_dm1_2",
    room_id: "dm_mama_akari",
    sender_id: "cast1",
    sender_name: "あかり",
    sender_role: "oneesan",
    content: "今月2回完了で、あと2件予定入ってます！渡辺様と伊藤様です",
    thread_parent_id: null,
    reply_count: 0,
    mentions_ai: false,
    is_bot: false,
    created_at: "2026-03-19T15:45:00+09:00",
  },
  {
    id: "msg_dm1_3",
    room_id: "dm_mama_akari",
    sender_id: "cast_mama1",
    sender_name: "さくら（ママ）",
    sender_role: "mama",
    content: "渡辺様の同伴の件、ありがとう。来月もよろしくね",
    thread_parent_id: null,
    reply_count: 0,
    mentions_ai: false,
    is_bot: false,
    created_at: "2026-03-19T16:00:00+09:00",
  },

  // ── dm_akari_misaki ──
  {
    id: "msg_dm2_1",
    room_id: "dm_akari_misaki",
    sender_id: "cast1",
    sender_name: "あかり",
    sender_role: "oneesan",
    content: "みさき、今日の営業で木村様がいらっしゃったら、静かめのテーブルにお願いね",
    thread_parent_id: null,
    reply_count: 0,
    mentions_ai: false,
    is_bot: false,
    created_at: "2026-03-19T17:00:00+09:00",
  },
  {
    id: "msg_dm2_2",
    room_id: "dm_akari_misaki",
    sender_id: "cast2",
    sender_name: "みさき",
    sender_role: "help",
    content: "了解！T5かT6あたりで準備しておきます",
    thread_parent_id: null,
    reply_count: 0,
    mentions_ai: false,
    is_bot: false,
    created_at: "2026-03-19T17:10:00+09:00",
  },
  {
    id: "msg_dm2_3",
    room_id: "dm_akari_misaki",
    sender_id: "cast1",
    sender_name: "あかり",
    sender_role: "oneesan",
    content: "明日のT3のお客様、お酒弱めだから最初は薄めで作ってね",
    thread_parent_id: null,
    reply_count: 0,
    mentions_ai: false,
    is_bot: false,
    created_at: "2026-03-19T17:30:00+09:00",
  },
];
