import type { ChatMessage, ChatRoom } from "../types";

// ═══════════════ Mock Chat Rooms ═══════════════
// Cast hierarchy:
//   ゆき (cast_oneesan2, 姉さん, top)
//     └─ あかり (cast1, 姉さん, middle)
//         └─ あやな (cast_help2, キャスト, bottom)
// さくらママは AI（ボット）なので cast ではない。

export const mockChatRooms: ChatRoom[] = [
  // ── Channels ──
  {
    id: "room_all",
    store_id: "store1",
    type: "channel",
    name: "全体連絡",
    member_ids: ["cast_oneesan2", "cast1", "cast_help2"],
    member_names: ["ゆき（姉さん）", "あかり", "あやな"],
    visible_to_seniors: true,
    created_at: "2026-01-01T00:00:00+09:00",
    last_message: {
      content: "明日のシフト確認お願いします",
      sender_name: "ゆき（姉さん）",
      sent_at: "2026-03-19T14:00:00+09:00",
    },
  },
  {
    id: "room_shift",
    store_id: "store1",
    type: "channel",
    name: "シフト相談",
    member_ids: ["cast_oneesan2", "cast1", "cast_help2"],
    member_names: ["ゆき（姉さん）", "あかり", "あやな"],
    visible_to_seniors: true,
    created_at: "2026-01-01T00:00:00+09:00",
    last_message: {
      content: "来週の金曜、お手伝いお願いできる？",
      sender_name: "あかり",
      sent_at: "2026-03-18T11:30:00+09:00",
    },
  },
  {
    id: "room_customer_share",
    store_id: "store1",
    type: "channel",
    name: "顧客情報共有",
    member_ids: ["cast_oneesan2", "cast1", "cast_help2"],
    member_names: ["ゆき（姉さん）", "あかり", "あやな"],
    visible_to_seniors: true,
    created_at: "2026-01-01T00:00:00+09:00",
    last_message: {
      content: "田中様、来週の水曜に来店予定です。担当テーブルにお願い",
      sender_name: "ゆき（姉さん）",
      sent_at: "2026-03-19T15:00:00+09:00",
    },
  },

  // ── 指導ルーム（coaching） ──
  {
    id: "coaching_yuki_akari",
    store_id: "store1",
    type: "coaching",
    name: "指導ノート — ゆき × あかり",
    member_ids: ["cast_oneesan2", "cast1"],
    member_names: ["ゆき（姉さん）", "あかり"],
    visible_to_seniors: false,
    created_at: "2026-01-15T00:00:00+09:00",
    last_message: {
      content: "今月は新規のLINE交換率を上げることを一緒に目指そう。困ったことあったらすぐ相談して",
      sender_name: "ゆき（姉さん）",
      sent_at: "2026-03-18T19:00:00+09:00",
    },
  },
  {
    id: "coaching_akari_ayana",
    store_id: "store1",
    type: "coaching",
    name: "指導ノート — あかり × あやな",
    member_ids: ["cast1", "cast_help2"],
    member_names: ["あかり", "あやな"],
    visible_to_seniors: true,
    created_at: "2026-02-01T00:00:00+09:00",
    last_message: {
      content: "先週の接客よかったよ。お客様のお名前をさりげなく使えてた",
      sender_name: "あかり",
      sent_at: "2026-03-17T22:00:00+09:00",
    },
  },

  // ── DMs ──
  {
    id: "dm_yuki_akari",
    store_id: "store1",
    type: "dm",
    name: null,
    member_ids: ["cast_oneesan2", "cast1"],
    member_names: ["ゆき（姉さん）", "あかり"],
    visible_to_seniors: false,
    created_at: "2026-02-01T00:00:00+09:00",
    last_message: {
      content: "渡辺様の同伴の件、ありがとう。来月もよろしくね",
      sender_name: "ゆき（姉さん）",
      sent_at: "2026-03-19T16:00:00+09:00",
    },
  },
  {
    id: "dm_akari_ayana",
    store_id: "store1",
    type: "dm",
    name: null,
    member_ids: ["cast1", "cast_help2"],
    member_names: ["あかり", "あやな"],
    visible_to_seniors: true, // ゆき姉さんが見れる
    created_at: "2026-02-15T00:00:00+09:00",
    last_message: {
      content: "明日のT3のお客様、お酒弱めだから最初は薄めで作ってね",
      sender_name: "あかり",
      sent_at: "2026-03-19T17:30:00+09:00",
    },
  },
];

// ═══════════════ Mock Chat Messages ═══════════════

export const mockChatMessages: ChatMessage[] = [
  // ── room_all: 全体連絡 ──
  {
    id: "msg_1",
    room_id: "room_all",
    sender_id: "cast_oneesan2",
    sender_name: "ゆき（姉さん）",
    sender_role: "oneesan",
    content: "みなさん、おはようございます。今週末は予約が多いのでシフトの確認をお願いします。",
    thread_parent_id: null,
    reply_count: 2,
    mentions_ai: false,
    is_bot: false,
    created_at: "2026-03-19T10:00:00+09:00",
  },
  {
    id: "msg_2",
    room_id: "room_all",
    sender_id: "cast1",
    sender_name: "あかり",
    sender_role: "oneesan",
    content: "確認しました！金曜と土曜は入れます🌸",
    thread_parent_id: "msg_1",
    reply_count: 0,
    mentions_ai: false,
    is_bot: false,
    created_at: "2026-03-19T10:15:00+09:00",
  },
  {
    id: "msg_3",
    room_id: "room_all",
    sender_id: "cast_help2",
    sender_name: "あやな",
    sender_role: "help",
    content: "土曜はOKです。金曜は確認します！",
    thread_parent_id: "msg_1",
    reply_count: 0,
    mentions_ai: false,
    is_bot: false,
    created_at: "2026-03-19T10:20:00+09:00",
  },
  {
    id: "msg_4",
    room_id: "room_all",
    sender_id: "cast_oneesan2",
    sender_name: "ゆき（姉さん）",
    sender_role: "oneesan",
    content: "明日のシフト確認お願いします",
    thread_parent_id: null,
    reply_count: 0,
    mentions_ai: false,
    is_bot: false,
    created_at: "2026-03-19T14:00:00+09:00",
  },

  // ── room_customer_share: 顧客情報共有 ──
  {
    id: "msg_cs_1",
    room_id: "room_customer_share",
    sender_id: "cast1",
    sender_name: "あかり",
    sender_role: "oneesan",
    content: "山本様が今週また来るみたい。ポルシェの話で盛り上がったから、次も車の話題で入ると良いかも",
    thread_parent_id: null,
    reply_count: 1,
    mentions_ai: false,
    is_bot: false,
    created_at: "2026-03-19T12:00:00+09:00",
  },
  {
    id: "msg_cs_2",
    room_id: "room_customer_share",
    sender_id: "cast_help2",
    sender_name: "あやな",
    sender_role: "help",
    content: "了解です！山本様のマッカラン、残り少なかったので追加キープ提案してみますか？",
    thread_parent_id: "msg_cs_1",
    reply_count: 0,
    mentions_ai: false,
    is_bot: false,
    created_at: "2026-03-19T12:10:00+09:00",
  },
  {
    id: "msg_cs_3",
    room_id: "room_customer_share",
    sender_id: "cast1",
    sender_name: "あかり",
    sender_role: "oneesan",
    content: "@さくらママ 山本様にボトルの追加キープを提案するタイミングはいつがベスト？",
    thread_parent_id: null,
    reply_count: 1,
    mentions_ai: true,
    is_bot: false,
    created_at: "2026-03-19T12:15:00+09:00",
  },
  {
    id: "msg_cs_4",
    room_id: "room_customer_share",
    sender_id: "sakura_mama",
    sender_name: "さくらママ",
    content: "山本様はVIPだから、残りが3杯以下になったタイミングがベストよ。「いつものを準備しておきますね」って自然に切り出すの。今のタイミングだと「この前のポルシェの話の続き、聞かせてくださいね。いつものマッカランも用意しておきますから」って感じかしら🌸",
    thread_parent_id: "msg_cs_3",
    reply_count: 0,
    mentions_ai: false,
    is_bot: true,
    created_at: "2026-03-19T12:15:30+09:00",
  },
  {
    id: "msg_cs_5",
    room_id: "room_customer_share",
    sender_id: "cast_oneesan2",
    sender_name: "ゆき（姉さん）",
    sender_role: "oneesan",
    content: "田中様、来週の水曜に来店予定です。担当テーブルにお願い",
    thread_parent_id: null,
    reply_count: 0,
    mentions_ai: false,
    is_bot: false,
    created_at: "2026-03-19T15:00:00+09:00",
  },

  // ── dm_yuki_akari ──
  {
    id: "msg_dm1_1",
    room_id: "dm_yuki_akari",
    sender_id: "cast_oneesan2",
    sender_name: "ゆき（姉さん）",
    sender_role: "oneesan",
    content: "あかり、今月の同伴の進捗はどう？",
    thread_parent_id: null,
    reply_count: 0,
    mentions_ai: false,
    is_bot: false,
    created_at: "2026-03-19T15:30:00+09:00",
  },
  {
    id: "msg_dm1_2",
    room_id: "dm_yuki_akari",
    sender_id: "cast1",
    sender_name: "あかり",
    sender_role: "oneesan",
    content: "今月2回完了で、あと2件予定入ってます！渡辺様と伊藤様です",
    thread_parent_id: null,
    reply_count: 0,
    mentions_ai: false,
    is_bot: false,
    created_at: "2026-03-19T15:45:00+09:00",
  },
  {
    id: "msg_dm1_3",
    room_id: "dm_yuki_akari",
    sender_id: "cast_oneesan2",
    sender_name: "ゆき（姉さん）",
    sender_role: "oneesan",
    content: "渡辺様の同伴の件、ありがとう。来月もよろしくね",
    thread_parent_id: null,
    reply_count: 0,
    mentions_ai: false,
    is_bot: false,
    created_at: "2026-03-19T16:00:00+09:00",
  },

  // ── coaching_yuki_akari ──
  {
    id: "cmsg_1",
    room_id: "coaching_yuki_akari",
    sender_id: "cast_oneesan2",
    sender_name: "ゆき（姉さん）",
    sender_role: "oneesan",
    content: "あかり、先月お疲れ様。今月の目標は売上150万・同伴4回にしてあるからね。\n\n今月のテーマ：新規顧客のLINE交換率を上げること。今の転換率が少し低いから、ここを重点的に。",
    thread_parent_id: null,
    reply_count: 1,
    mentions_ai: false,
    is_bot: false,
    created_at: "2026-03-01T10:00:00+09:00",
  },
  {
    id: "cmsg_2",
    room_id: "coaching_yuki_akari",
    sender_id: "cast1",
    sender_name: "あかり",
    sender_role: "oneesan",
    content: "ありがとうございます！LINE交換、自分からお願いするのがちょっと苦手で…どんなタイミングで聞くといいですか？",
    thread_parent_id: "cmsg_1",
    reply_count: 0,
    mentions_ai: false,
    is_bot: false,
    created_at: "2026-03-01T11:30:00+09:00",
  },
  {
    id: "cmsg_3",
    room_id: "coaching_yuki_akari",
    sender_id: "cast_oneesan2",
    sender_name: "ゆき（姉さん）",
    sender_role: "oneesan",
    content: "帰り際のタイミングが一番自然よ。「また来てくださいね、LINEつながっておけば次回の予約もスムーズですよ」って感じで。押し売りじゃなく、お客様のメリットとして伝えるのがコツ。",
    thread_parent_id: null,
    reply_count: 0,
    mentions_ai: false,
    is_bot: false,
    created_at: "2026-03-01T12:00:00+09:00",
  },
  {
    id: "cmsg_4",
    room_id: "coaching_yuki_akari",
    sender_id: "cast_oneesan2",
    sender_name: "ゆき（姉さん）",
    sender_role: "oneesan",
    content: "今月は新規のLINE交換率を上げることを一緒に目指そう。困ったことあったらすぐ相談して",
    thread_parent_id: null,
    reply_count: 0,
    mentions_ai: false,
    is_bot: false,
    created_at: "2026-03-18T19:00:00+09:00",
  },

  // ── coaching_akari_ayana ──
  {
    id: "cmsg_a1",
    room_id: "coaching_akari_ayana",
    sender_id: "cast1",
    sender_name: "あかり",
    sender_role: "oneesan",
    content: "あやな、今月の目標は売上80万・同伴2回ね。まずは接客の基本を固めることが大事だから、焦らなくていいよ。\n\n今月のテーマ：お客様のお名前を自然に使う接客。",
    thread_parent_id: null,
    reply_count: 1,
    mentions_ai: false,
    is_bot: false,
    created_at: "2026-03-01T10:00:00+09:00",
  },
  {
    id: "cmsg_a2",
    room_id: "coaching_akari_ayana",
    sender_id: "cast_help2",
    sender_name: "あやな",
    sender_role: "help",
    content: "わかりました！お名前を使うの、意識してみます。昨日の田中様への接客、あかり姉さんどう見えましたか？",
    thread_parent_id: "cmsg_a1",
    reply_count: 0,
    mentions_ai: false,
    is_bot: false,
    created_at: "2026-03-01T11:00:00+09:00",
  },
  {
    id: "cmsg_a3",
    room_id: "coaching_akari_ayana",
    sender_id: "cast1",
    sender_name: "あかり",
    sender_role: "oneesan",
    content: "先週の接客よかったよ。お客様のお名前をさりげなく使えてた",
    thread_parent_id: null,
    reply_count: 0,
    mentions_ai: false,
    is_bot: false,
    created_at: "2026-03-17T22:00:00+09:00",
  },

  // ── dm_akari_ayana ──
  {
    id: "msg_dm2_1",
    room_id: "dm_akari_ayana",
    sender_id: "cast1",
    sender_name: "あかり",
    sender_role: "oneesan",
    content: "あやな、今日の営業で木村様がいらっしゃったら、静かめのテーブルにお願いね",
    thread_parent_id: null,
    reply_count: 0,
    mentions_ai: false,
    is_bot: false,
    created_at: "2026-03-19T17:00:00+09:00",
  },
  {
    id: "msg_dm2_2",
    room_id: "dm_akari_ayana",
    sender_id: "cast_help2",
    sender_name: "あやな",
    sender_role: "help",
    content: "了解！T5かT6あたりで準備しておきます",
    thread_parent_id: null,
    reply_count: 0,
    mentions_ai: false,
    is_bot: false,
    created_at: "2026-03-19T17:10:00+09:00",
  },
  {
    id: "msg_dm2_3",
    room_id: "dm_akari_ayana",
    sender_id: "cast1",
    sender_name: "あかり",
    sender_role: "oneesan",
    content: "明日のT3のお客様、お酒弱めだから最初は薄めで作ってね",
    thread_parent_id: null,
    reply_count: 0,
    mentions_ai: false,
    is_bot: false,
    created_at: "2026-03-19T17:30:00+09:00",
  },
];
